name: 522-lec1
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - icu=75.1=hfee45f7_0
  - libblas=3.11.0=1_h51639a9_openblas
  - libcblas=3.11.0=1_hb0561ab_openblas
  - libcxx=21.1.6=hf598326_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.5.2=he5f378a_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - liblapack=3.11.0=1_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libopenblas=0.3.30=openmp_ha158390_3
  - libsqlite=3.51.0=h8adb53f_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.5=h4a912ad_2
  - ncurses=6.5=h5e97a16_3
  - numpy=2.3.5=py311h8685306_0
  - openssl=3.6.0=h5503f6c_0
  - pandas=2.3.3=py311hdb8e4fa_1
  - pip=25.3=pyh8b19718_0
  - python=3.11.14=h18782d2_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - readline=8.2=h1d1bf99_2
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - tk=8.6.13=h892fb3f_3
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
prefix: /Users/nguyenuyennguyen/Miniforge3-Darwin-arm64/envs/522-lec1
